### ISSUE TITLE
Attributes support?

### ISSUE THREAD

**Issue by dajacques** [apiaryio/redsnow#60]
Does redsnow support attributes? I don't see anything to indicate that it does. If not, any plans to support them?

**Comment by zdne** [comment]
Hey @dajacques we are currently slowly rolling out the attributes in our infrastructure. Attributes support in Red Snow is definitely planned!

Currently the MSON (attributes syntax) [AST](https://github.com/apiaryio/mson-ast) is available [internally](https://github.com/apiaryio/redsnow/blob/master/lib/redsnow/binding.rb#L26) inside Red Snow, however it not wrapped in Ruby classes. 

PS: Any contributions are welcome!

**Comment by dajacques** [comment]
Perfect. Thanks for the feedback. I wanted to make sure I wasn't missing something before digging too deeply.
