### ISSUE TITLE
Prepare travis to deploy gem into rubygems

### ISSUE THREAD

**Issue by abtris** [apiaryio/redsnow#62]
http://docs.travis-ci.com/user/deployment/rubygems/

**Comment by zdne** [comment]
@abtris can you please elaborate?

**Comment by abtris** [comment]
I think we can release to rubygems using travisCI instead manual `gem push`.

**Comment by zdne** [comment]
@abtris we are definitely going to look into this as we are planning to create some parser toolchain release scripts. Thanks!

**Comment by kylef** [comment]
Closing as redsnow is deprecated and there will be no future development of this library.
