### ISSUE TITLE
Missing files in redsnow-0.4.2.gem

### ISSUE THREAD

**Issue by tobiashm** [apiaryio/redsnow#68]
The released gem file for v0.4.2 is missing the `ext/` folder.

If you look at [the redsnow gem page on rubygems.org](https://rubygems.org/gems/redsnow) it is also clear that something is missing, as the file size is much smaller than usually:

> VERSIONS:
> 0.4.2 - July 7, 2015 (13.5 KB)
> 0.4.1 - April 24, 2015 (8.43 MB)
> 0.4.0 - March 30, 2015 (7.37 MB)
> 0.3.7 - March 25, 2015 (2.59 MB)
> 0.3.4 - December 16, 2014 (3.32 MB)

I've tried building the gem myself and it went fine, so it's probably just a bad build that was pushed.

Since rubygems.org does not allow for re-publishing a gem version, I would suggest yanking v0.4.2 (`gem yank redsnow -v 0.4.2`) and publishing a new version.

**Comment by abtris** [comment]
Good point, I look into.

**Comment by tobiashm** [comment]
Great, thanks.

**Comment by abtris** [comment]
Invalid gem (v0.4.2) was removed from rubygems.
