### ISSUE TITLE
Complete Sample??

### ISSUE THREAD

**Issue by zotherstupidguy** [apiaryio/redsnow#72]
`require 'redsnow'                                                                                                                                                  

file = File.open("apiblueprint").read
result = RedSnow::parse(file)
puts result.ast.name
puts result.sourcemap.name`

I am trying to make this work, but getting trouble understanding how redsnow works, could you please add a more descriptive example in the homepage?

**Comment by zdne** [comment]
Hey @zotherstupidguy sorry for the confusion. I think you are using Red Snow correctly. What this version offers is the (now deprecated) API Blueprint AST. Check the https://github.com/apiaryio/redsnow/blob/master/lib/redsnow/blueprint.rb#L346 for available data. 

Note Red Snow is currently using an older version of the API Blueprint parser and no update is currently planned. Unless someone is going to update it I would suggest to use alternative way to parse API Blueprint in a Ruby program. See https://github.com/apiaryio/api-blueprint/wiki/Developers for details on how to develop tools for API Blueprint.

**Comment by zotherstupidguy** [comment]
@zdne Many thanks for your reply, i quickly moved to https://github.com/tripit/slate which I guess is good enough for my current needs at the moment, thanks again :+1:
