### ISSUE TITLE
Building extension suddenly starts producing errors

### ISSUE THREAD

**Issue by dgmora** [apiaryio/redsnow#74]
I realize that there's a very similar issue, but as the other one is old and the stacktrace is different i think it's better to file a new issue. We have been using redsnow for a while, and (apparently) without changing anything, installing the gem fails with the following message:

```
Cannot load bundler/gem_tasks
Path to library /home/ubuntu/zeta/vendor/bundle/ruby/2.3.0/gems/redsnow-0.4.3/ext/drafter/build/out/Release/lib.target/libdrafter.so
Compiling extension...
../src/config.cc:11:21: fatal error: cmdline.h: No such file or directory
 #include "cmdline.h"
                     ^
compilation terminated.
make[1]: *** [out/Release/obj.target/drafter/src/config.o] Error 1
make: *** [drafter] Error 2
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x000000026d7bb0>
```

If we take an older version of our gem using `redsnow` and try to rebuild it, it also fails. Even if it worked in the past.

Thanks in advance!

**Comment by kylef** [comment]
Hi @dgmora,

We haven't been maintaining this library and it is pretty outdated.

I think the best approach for API Blueprint parsing in Ruby going forward would be to use libffi with Drafter. You can install [Drafter](https://github.com/apiaryio/drafter) and then use Drafter directly from Ruby (https://github.com/apiaryio/drafter/pull/356#issuecomment-229733343).

**Comment by dgmora** [comment]
Thanks for the fix @tobiashm, that'll be handy. In case anyone is interested, I've implemented a binding for the method I needed: https://github.com/moviepilot/lounge_lizard
Will there be a release for this fix?

**Comment by pksunkara** [comment]
@dgmora We are very close to releasing drafter v4. It might include a few minor api changes. Please do keep track of it and update you library accordingly. Thanks.

**Comment by dgmora** [comment]
Sure, will do. 

Regarding Redsnow, will there be a 0.4.4 with #76 ?

**Comment by pksunkara** [comment]
Yeah, https://github.com/apiaryio/redsnow/pull/77
